 #define F_CPU 16000000UL
#include <avr/io.h>
#include <util/delay.h>

int main(void)
{
    DDRB = (1 << PB2);  // PB0 output

    while (1)
    {
        PORTB |= (1 << PB0);   // ON
        _delay_ms(1000);

        PORTB &= ~(1 << PB0);  // OFF
        _delay_ms(1000);
    }
}
 